version: "3.9"

x-env: &common-env
  PUID: "${PUID:-1000}"
  PGID: "${PGID:-1000}"
  TZ:   "${TZ:-Asia/Shanghai}"

x-restart: &restart { restart: unless-stopped }
x-logging: &logging
  logging:
    driver: json-file
    options: { max-size: "10m", max-file: "3" }

networks:
  proxy: { external: true }
  media: { internal: true }

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      <<: *common-env
      WEBUI_PORT: "${QBIT_PORT_UI:-8080}"
    volumes:
      - "${MEDIA_STACK_ROOT:-/data/apps}/qbittorrent/config:/config"
      - "${MEDIA_STACK_ROOT:-/data/apps}/qbittorrent/downloads:/downloads"
      - "${MEDIA_STACK_ROOT:-/data/apps}/qbittorrent/watch:/watch"
      - "${MEDIA_STACK_ROOT:-/data/apps}/qbittorrent/logs:/logs"
    ports:
      - "${QBIT_PORT_UI:-8080}:8080"
      - "6881:6881"
      - "6881:6881/udp"
    networks: [media, proxy]
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8080"]
      interval: 30s
      timeout: 5s
      retries: 5
    <<: [*restart, *logging]
