x-restart: &restart { restart: unless-stopped }
x-logging: &logging
  logging:
    driver: json-file
    options: { max-size: "10m", max-file: "3" }

services:
  valheim-server:
    image: ghcr.io/lloesche/valheim-server
    container_name: valheim-server
    cap_add:
      - sys_nice
    stop_grace_period: 120s
    environment:
      TZ: "${TZ:-Asia/Taipei}"
      SERVER_NAME: "${VALHEIM_SERVER_NAME:-JavaZero Server}"
      WORLD_NAME: "${VALHEIM_WORLD_NAME:-wtfsbsbsbsb}"
      SERVER_PASS: "${VALHEIM_SERVER_PASS:?Set VALHEIM_SERVER_PASS in .env}"
      SERVER_PUBLIC: "${VALHEIM_SERVER_PUBLIC:-true}"
    ports:
      - "2456-2457:2456-2457/udp"
    volumes:
      - "./config:/config"
      - "./data:/opt/valheim"
    <<: [*restart, *logging]
